/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.88
 * Generated at: 2024-05-13 13:30:37 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Admin_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/Users/LOGITECH/Desktop/doctor/New%20folder/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/echanneling/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153365282000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1715354972256L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write(" \r\n");
      out.write("    \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write(" <title>Admin profile</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"CSS/admin1.css\">\r\n");
      out.write("  </head>\r\n");
      out.write("  <body>\r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("  <div class=\"login\">\r\n");
      out.write("    <img src=\"Images/logo.png\" id=\"logo\" alt=\"channel logo\">\r\n");
      out.write("    <img src=\"Images/title1.png\" id=\"title\" alt=\"channel title\">\r\n");
      out.write("    <img src=\"Images/worker.png\" id=\"pImg\" alt=\"profile image\">\r\n");
      out.write("  </div>  \r\n");
      out.write("  <div class=\"Aname\">  \r\n");
      out.write("	<h3>Admin Name  </h3>\r\n");
      out.write("    <a href=\"Home.jsp\" id=\"logout\" ><button>Log out</button></a>\r\n");
      out.write("  </div>	\r\n");
      out.write("  \r\n");
      out.write("\r\n");
      out.write("  \r\n");
      out.write("<!--navigation bar-->\r\n");
      out.write("<div class=\"navBarDiv\">\r\n");
      out.write("    <div class=\"topnav\">\r\n");
      out.write("    <a href=\"Home.jsp\">Home</a>\r\n");
      out.write("    <a href=\"aboutUs.jsp\">About Us</a>\r\n");
      out.write("    <a href=\"ourfacility.jsp\">Our Facilities</a>\r\n");
      out.write("    <a href=\"contactUs.jsp\">Contact Us</a>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("      <div class=\"search\">\r\n");
      out.write("        <form style=\"height: 100%;\" onsubmit=\"return false\">\r\n");
      out.write("          <input type=\"search\" placeholder=\"Search in our website...\" id=\"searchBar\" onsearch=\"search()\">\r\n");
      out.write("          <img src=\"Images/search.png\"> \r\n");
      out.write("          <script src=\"JS/searchBar.js\"></script>\r\n");
      out.write("          <input type=\"submit\" id=\"searchSubmit\">\r\n");
      out.write("        </form>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	\r\n");
      out.write("<!-- charts-->	\r\n");
      out.write("  <div class=\"cons\">\r\n");
      out.write("     <h2>Dashboard</h2>\r\n");
      out.write("     <hr>\r\n");
      out.write("  	 \r\n");
      out.write("     <div id=\"Patient\">\r\n");
      out.write("        <div id=\"patient\">\r\n");
      out.write("           <img src=\"Images/hart.png\">\r\n");
      out.write("           <h1><b>Total patient</b></h1>\r\n");
      out.write("           <h2>800k</h2>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  \r\n");
      out.write("    <div id=\"Doc\">\r\n");
      out.write("        <div id=\"doc\">\r\n");
      out.write("           <img src=\"Images/steth.png\" >\r\n");
      out.write("           <h1><b>Doctor</b></h1>\r\n");
      out.write("           <h2>200</h2>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div id=\"Appoin\">\r\n");
      out.write("        <div id=\"appoin\">\r\n");
      out.write("           <img src=\"Images/calender.png\" >\r\n");
      out.write("           <h1>Appoinment</h1>\r\n");
      out.write("           <h2>400</h2>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("<!--charts-->\r\n");
      out.write("    <div id=\"Chart\">\r\n");
      out.write("        <div id=\"chart\">\r\n");
      out.write("           <img src=\"Images/revenue.png\" >\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("   \r\n");
      out.write("<!--manage user-->\r\n");
      out.write("<div class=\"manage\">\r\n");
      out.write("    <h2>Manage admin account</h2>\r\n");
      out.write("    <hr>\r\n");
      out.write("    </div>\r\n");
      out.write("<!--information-->\r\n");
      out.write("    <div class=\"info\">\r\n");
      out.write("        <form>\r\n");
      out.write("          <h2>Personal Information</h2>\r\n");
      out.write("          <h4>Update your personal information</h4>\r\n");
      out.write("          <label for=\"fName\">First Name</label>\r\n");
      out.write("          <input type=\"text\" id=\"fName\" name=\"first_name\" placeholder=\"First Name\"  class=\"textbox\">\r\n");
      out.write("      \r\n");
      out.write("          <label for=\"lName\">Last Name</label>\r\n");
      out.write("          <input type=\"text\" id=\"lName\" name=\"first_name\" placeholder=\"Last Name\"  class=\"textbox\"><br>\r\n");
      out.write("        \r\n");
      out.write("          <label for=\"date\" class=\"dobLabel\">Birthday</label>\r\n");
      out.write("            <select name=\"day\" id=\"date\" >\r\n");
      out.write("              <option disabled selected hidden>dd</option>\r\n");
      out.write("              <option>1</option>\r\n");
      out.write("              <option>2</option>\r\n");
      out.write("              <option>3</option>\r\n");
      out.write("              <option>4</option>\r\n");
      out.write("              <option>5</option>\r\n");
      out.write("              <option>6</option>\r\n");
      out.write("              <option>7</option>\r\n");
      out.write("              <option>8</option>\r\n");
      out.write("              <option>9</option>\r\n");
      out.write("              <option>10</option>\r\n");
      out.write("              <option>11</option>\r\n");
      out.write("              <option>12</option>\r\n");
      out.write("              <option>13</option>\r\n");
      out.write("              <option>14</option>\r\n");
      out.write("              <option>15</option>\r\n");
      out.write("              <option>16</option>\r\n");
      out.write("              <option>17</option>\r\n");
      out.write("              <option>18</option>\r\n");
      out.write("              <option>19</option>\r\n");
      out.write("              <option>20</option>\r\n");
      out.write("              <option>21</option>\r\n");
      out.write("              <option>22</option>\r\n");
      out.write("              <option>23</option>\r\n");
      out.write("              <option>24</option>\r\n");
      out.write("              <option>25</option>\r\n");
      out.write("              <option>26</option>\r\n");
      out.write("              <option>27</option>\r\n");
      out.write("              <option>28</option>\r\n");
      out.write("              <option>29</option>\r\n");
      out.write("              <option>30</option>\r\n");
      out.write("              <option>31</option>\r\n");
      out.write("            </select>\r\n");
      out.write("            <select name=\"month\" id=\"month\">\r\n");
      out.write("              <option disabled selected hidden>mm</option>\r\n");
      out.write("              <option>Jan</option>\r\n");
      out.write("              <option>Feb</option>\r\n");
      out.write("              <option>Mar</option>\r\n");
      out.write("              <option>Apr</option>\r\n");
      out.write("              <option>May</option>\r\n");
      out.write("              <option>Jun</option>\r\n");
      out.write("              <option>Jul</option>\r\n");
      out.write("              <option>Aug</option>\r\n");
      out.write("              <option>Sep</option>\r\n");
      out.write("              <option>Oct</option>\r\n");
      out.write("              <option>Nov</option>\r\n");
      out.write("              <option>Dec</option>\r\n");
      out.write("            </select>\r\n");
      out.write("            <select  name=\"year\" id=\"year\">\r\n");
      out.write("              <option disabled selected hidden>yyyy</option>\r\n");
      out.write("              <option>1995</option>\r\n");
      out.write("              <option>1996</option>\r\n");
      out.write("              <option>1997</option>\r\n");
      out.write("              <option>1998</option>\r\n");
      out.write("              <option>1999</option>\r\n");
      out.write("              <option>2000</option>\r\n");
      out.write("              <option>2001</option>\r\n");
      out.write("              <option>2002</option>\r\n");
      out.write("              <option>2003</option>\r\n");
      out.write("              <option>2004</option>\r\n");
      out.write("              <option>2005</option>\r\n");
      out.write("            </select><br><br>\r\n");
      out.write("      \r\n");
      out.write("          <label for=\"Address\">Address</label>\r\n");
      out.write("          <input type=\"text\" id=\"Address\" name=\"first_name\" placeholder=\"Address\"  class=\"textbox\"><br>\r\n");
      out.write("      \r\n");
      out.write("          <label for=\"email\">Email Address</label>\r\n");
      out.write("          <img src=\"Images/m1.png\" alt=\"email icon\" class=\"emailIcon\">\r\n");
      out.write("          <input type=\"text\" id=\"email\" name=\"first_name\" placeholder=\"Email Address\"  class=\"textbox\">\r\n");
      out.write("      \r\n");
      out.write("          <label for=\"pNo\">Phone number</label>\r\n");
      out.write("          <img src=\"Images/pi.png\" alt=\"phone icon\" class=\"phoneIcon\">\r\n");
      out.write("          <input type=\"text\" id=\"pNo1\" name=\"first_name\" placeholder=\"Phone Number\"  class=\"textbox\">\r\n");
      out.write("          <input type=\"submit\" value=\"Save Changes\" id=\"scalert\">\r\n");
      out.write("          <a href=\"#\" id=\"edit\" ><button>Edit</button></a>\r\n");
      out.write("        </form>\r\n");
      out.write("       </div>\r\n");
      out.write("       \r\n");
      out.write("       \r\n");
      out.write("\r\n");
      out.write("       <!--Security-->\r\n");
      out.write("\r\n");
      out.write("  <div class=\"secu\">\r\n");
      out.write("    <form onsubmit=\"return checkPasswordOnChange()\">\r\n");
      out.write("      <h2>Security Information</h2>\r\n");
      out.write("      <h4>Your new password must be different from previous used password</h4>\r\n");
      out.write("  \r\n");
      out.write("      <label for=\"currentPassword\">Current Password</label>\r\n");
      out.write("      <img src=\"Images/l1.png\" alt=\"phone icon\" class=\"lockIcon\">\r\n");
      out.write("      <input type=\"password\" id=\"currentPassword\" name=\"currentPassword\" placeholder=\"Current Password******\" class=\"textbox\"><br>\r\n");
      out.write("  \r\n");
      out.write("      <label for=\"newPassword\">New Password</label>\r\n");
      out.write("      <img src=\"Images/l1.png\" alt=\"phone icon\" class=\"lockIcon\">\r\n");
      out.write("      <input type=\"password\" id=\"newPassword\" name=\"newPassword\" placeholder=\" New Password******\" class=\"textbox\" pattern=\"(?=.*\\d)(?=.*[a-z])(?=.*[A-Z]).{8,}\" title=\"Must contain at least one number and one uppercase and lowercase letter, and at least 8 or more characters\">\r\n");
      out.write("  \r\n");
      out.write("      <label for=\"confirmNewPassword\">Confirm New Password</label>\r\n");
      out.write("      <img src=\"Images/l1.png\" alt=\"phone icon\" class=\"lockIcon\">\r\n");
      out.write("      <input type=\"password\" id=\"confirmNewPassword\" name=\"password\" placeholder=\"Confirm New Password*****\" class=\"textbox\">\r\n");
      out.write("  \r\n");
      out.write("      <input type=\"submit\" value=\"Save Changes\" id=\"scalert\">\r\n");
      out.write("      <a href=\"#\" id=\"edit\" ><button>Edit</button></a>\r\n");
      out.write("    </form>\r\n");
      out.write("  </div>\r\n");
      out.write("     <a href=\"#\" > <button id=\"delete\">Delete</button></a>\r\n");
      out.write("     <a href=\"AddAdmin.jsp\" > <button id=\"add\">Add Admin</button></a>\r\n");
      out.write("\r\n");
      out.write("    <!--footer-->\r\n");
      out.write("    <footer>\r\n");
      out.write("        <br><br>\r\n");
      out.write("        <table width=\"30%\" class=\"footerTable\">\r\n");
      out.write("          <tr>\r\n");
      out.write("            <td width=\"20%\">Contact Us,</td>\r\n");
      out.write("            <td width=\"10%\"><img src=\"Images/email.png\" width=\"80%\"></td>\r\n");
      out.write("            <td style=\"white-space:nowrap; text-align: left;\">helthgrade@gmail.com</td>\r\n");
      out.write("          </tr>\r\n");
      out.write("          <tr>\r\n");
      out.write("            <td></td>\r\n");
      out.write("            <td><img src=\"Images/phone.png\" width=\"55%\"></td>\r\n");
      out.write("            <td style=\"text-align: left;\">+94 (70) 123 4567</td>\r\n");
      out.write("          </tr>\r\n");
      out.write("        </table><br><br><br>\r\n");
      out.write("    \r\n");
      out.write("        <table width=\"30%\" class=\"footerTable footerTableHover\">\r\n");
      out.write("          <tr>\r\n");
      out.write("            <td>Follow Us On,</td>\r\n");
      out.write("            <td width=\"10%\"><a href=\"https://www.facebook.com/\" target=\"_blank\"><img src=\"Images/facebook.png\" class=\"fb\"></a></td>\r\n");
      out.write("            <td width=\"10%\"><a href=\"https://www.instagram.com/\" target=\"_blank\"><img src=\"Images/insta.png\" class=\"insta\"></a></td>\r\n");
      out.write("            <td width=\"10%\"><a href=\"https://www.youtube.com/\" target=\"_blank\"><img src=\"Images/youtube.png\" class=\"yt\"></a></td>\r\n");
      out.write("            \r\n");
      out.write("            <td width=\"60%\"></td>\r\n");
      out.write("          </tr>\r\n");
      out.write("        </table><br>\r\n");
      out.write("    \r\n");
      out.write("        <div class=\"address\">\r\n");
      out.write("          <h2>Healthgrade (pvt) Ltd</h2>\r\n");
      out.write("          <p>Street: 568 Havelock Road,<br>06th Lane, Colombo</p>\r\n");
      out.write("        </div>\r\n");
      out.write("    \r\n");
      out.write("        <div class=\"hyperLinks\">\r\n");
      out.write("          <p>\r\n");
      out.write("            <a href=\"aboutUs.jsp\">About Us</a> |\r\n");
      out.write("            <a href=\"contactUs.jsp\">Contact Us</a> |\r\n");
      out.write("            <a href=\"FAQ.jsp\">FAQ</a> |\r\n");
      out.write("            <a href=\"customerSupport.jsp\">Customer Support</a> | \r\n");
      out.write("            <a href=\"CustomerFeedback.jsp\">Customer Feedback</a>\r\n");
      out.write("          </p>\r\n");
      out.write("        </div>\r\n");
      out.write("        <br><br>\r\n");
      out.write("    \r\n");
      out.write("        <div class=\"bottomLogo\">\r\n");
      out.write("          <img src=\"Images/logo.png\">\r\n");
      out.write("          <p>&copy; 2023 Helthgrade. All rights reserved.</p>\r\n");
      out.write("        </div>\r\n");
      out.write("    \r\n");
      out.write("      </footer>\r\n");
      out.write("    </body>\r\n");
      out.write("  </html>\r\n");
      out.write("  \r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
